# Generated by Django 3.1.7 on 2021-02-26 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='has_referred', to=settings.AUTH_USER_MODEL)),
                ('referred_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_query_name='my_referral', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
