# Generated by Django 3.1.7 on 2021-02-26 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0002_referral'),
    ]

    operations = [
        migrations.RenameField(
            model_name='referral',
            old_name='new_user',
            new_name='referred_to',
        ),
    ]
