# Generated by Django 3.1.7 on 2021-02-28 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0004_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='credits',
            field=models.FloatField(default=0.0),
        ),
    ]
